### PR TITLE
`directory_iterator` throws.

### LINKED ISSUE #73: `directory_iterator` will throw if the path no longer exists.
`imfilebrowser.h:1023` in `UpdateFileRecords()`
```c++
for(auto &p : std::filesystem::directory_iterator(currentDirectory_))
```
`directory_iterator` will throw if the path no longer exists. I found it by selecting a path and then moving it and going to open the browser again.

I plan to create a pull request. By adding some try/catch handling for this maybe wrap it in a lambda.

Here is the related issue in my project: https://github.com/Sebanisu/Field-Map-Editor/issues/169

### LINKED ISSUE #169: Browse button on batch operation screen can crash
You click browse select a directory. Then move that directory or rename it to something else. Then click browse again it crashes. This might be upstream. I'll need to look into it. Because the filebrowser is another project.

### PR DESCRIPTION
**Pull request by Sebanisu**
fixes: https://github.com/AirGuanZ/imgui-filebrowser/issues/73
fixes: https://github.com/Sebanisu/Field-Map-Editor/issues/169

image

I noticed if you selected a path in the browser. Made the path not exist. Then reopen the browser it would throw. So I added a lambda wrapper around the call that does a try/catch. The catch sets statusStr_ and uses the ImGuiFileBrowserFlags_SkipItemsCausingError to see if we should rethrow or not.

I hope this will be acceptable.

I also added a tooltip to statusStr_ because it was getting cut off. I added text wrapping to the tooltip because it was so long.
```c++
ImGui::BeginTooltip();            
ImGui::PushTextWrapPos(300.0f);
ImGui::Text("%s", statusStr_.c_str());
ImGui::PopTextWrapPos();
ImGui::EndTooltip();
```

### CODE REVIEW

**Comment by Sebanisu** [comment]
I changed to 200.0f pixels might try 300.0f. I wonder why it's wrapping after the first `"`.
image

**Comment by Sebanisu** [comment]
image

This is changed to 300.0f pixels I think it looks better.

File: imfilebrowser.h [hunk 1]
```diff
@@ -1020,7 +1028,24 @@ inline void ImGui::FileBrowser::UpdateFileRecords()
 {
     fileRecords_ = { FileRecord{ true, "..", "[D] ..", "" } };
 
-    for(auto &p : std::filesystem::directory_iterator(currentDirectory_))
+    const auto get_directory_iterator = [&]() -> std::filesystem::directory_iterator
```
Comment (AirGuanZ) [inline imfilebrowser.h]: `get_directory_iterator` has an inconsistent naming style

**Comment by AirGuanZ** [comment]
Thank you for the PR! Both changes look great. There is a minor inconsistency in the naming style (`get_directory_iterator`). I would be glad to merge the PR once it's fixed.

**Comment by Sebanisu** [comment]
I changed get_directory_iterator -> getDirectoryIterator I think that's right. if not it'd be GetDirectoryIterator. heh

**Comment by AirGuanZ** [comment]
Looks good now. Thank you very much!
